In [1]:
import numpy as np

In [4]:
arr = np.arange(9).reshape((3,3))
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [5]:
arr.T

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

In [6]:
arr.transpose()

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

In [7]:
arr.transpose((0,1))

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [8]:
arr.transpose((1,0))

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

In [9]:
arr.swapaxes(1,0)
#ここわからない

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

In [12]:
arr.swapaxes(0,1)

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

In [13]:
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [15]:
np.dot(arr.T,arr)

array([[45, 54, 63],
       [54, 66, 78],
       [63, 78, 93]])